### ISSUE TITLE
Implement file inclusion while avoiding collisions

### ISSUE THREAD

**Issue by AvtechScientific** [Zacharymk1213/darjot.js#1]
1. Implement file inclusion (both text files and images) with the full syntax `+[alt text]<path/to/file>` and the corresponding short syntax `+<path/to/file>`  while avoiding collisions (e.g. same footnote labels in different included files).
2. Add relevant unit tests to the code and enable them in the CI.
3. Especially add a test for colliding footnotes (both numerical and alphabetical labels). Post a link of it's passing in the CI here.

**Comment by Zacharymk1213** [comment]
https://github.com/Zacharymk1213/darjot.js/blob/main/src/dar_specific_tests.spec.ts - here's the unit tests

https://github.com/Zacharymk1213/darjot.js/actions/runs/9823945398/job/27122379048 here's these tests running successfully. Both forms of file inclusion are also tested. Good thing you had me do all these tests. There was a logic error with the short syntax I overlooked that was causing it to not fall back to the alt text that I fixed.

Currently I decided that if alt text is provided it uses that. If the file isn't found in short syntax then the string is rendered literally with all it's syntax (I think malformed HTML is often displayed in a similar way so this would have a precedent)

**Comment by Zacharymk1213** [comment]
I found another error. The warning wasn't being triggered for the short syntax because the loop wasn't being entered but only on the last line (really weird error and easy to miss.) Fixed this and added unit tests testing for specifically this. I also switched it to error out if there's no fallback alt text. A warning is provided if alt text is provided. 

Addressed in this commit: e2c3e1c870941f1052ca7565ff4e92babb8d15ff
https://github.com/Zacharymk1213/darjot.js/actions/runs/9824499148/job/27123548027 - Here's the test case passing

**Comment by AvtechScientific** [comment]
1. We should aim at merging as much code as possible upstream to djot. This feature is of general importance and a good candidate for a merge. Please avoid texts, names and id's in Hebrew or relevant to Pninim (e.g. "Rav Hirsch wrote many Seforim", etc.). Use neutral, synthetic language...

**Comment by AvtechScientific** [comment]
2. [Dar's footnote syntax](https://gitlab.com/pninim.org/dar/dar-syntax/-/blob/master/syntax.dar?ref_type=heads#L224) defines the footnote body as follows (without ":"):

```
Sentence of the first [^a]paragraph. 

[^a] Sentence of a long margin note's body that refers to the word "paragraph".
```

and not `[^a]: Sentence of a long margin note's body that refers to the word "paragraph".`

See [here](https://github.com/Zacharymk1213/darjot.js/blob/main/test_files/inclusions_with_footnotes/doc4.dj#L3)

**Comment by Zacharymk1213** [comment]
Done to all of these. Also cleaned up how footnotes were handled in general.

**Comment by AvtechScientific** [comment]
I think the proper behavior regarding the alt text / missing files should be the following:
1. long form inclusion (which contains alt text) `+[alt text]<path/to/file>` in a case that requested file is missing should dump `[alt text` in place of inclusion and WARN.
2. short form inclusion (which on purpose doesn't contain alt text) `+<path/to/file>` in a case that requested file is missing should ERROR out and stop parsing.

**Comment by Zacharymk1213** [comment]
That's the current behavior.
